### ISSUE TITLE
Is it possible to bind dynamic parameters?

### ISSUE THREAD

**Issue by Airfly** [dotnet9/AvaloniaExtensions#2]
codes look likes photo below:
![binding dynamic parameters](https://github.com/user-attachments/assets/46f4d17d-ca60-46e1-8dc6-aaf804e54b45)

**Comment by dotnet9** [comment]
Thank you for raising this issue. Whether you are using Resx resource files or custom XML files to store internationalization resources, the usage is the same. For example, if you have the following two resource keys:

```shell
RunningCountInfo = Running {0} operating system, {1}
CurrentTimeFormat = The current time is {0}
```

The usage with constant parameters or bound properties is as follows:

```axaml
<TextBlock Text="{markup:I18n {Binding Title}}" />
<TextBlock Text="{markup:I18n {x:Static l:Language.Welcome}}" />
<TextBlock Text="{markup:I18n {x:Static l:Language.RunningCountInfo}, Win11, x64}" />
<TextBlock Text="{markup:I18n {x:Static l:Language.CurrentTimeFormat}, {Binding CurrentTime}}" />
```

You can refer to the Demo for detailed usage.

Thanks again for your feedback.
